# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{urlsplease-imposter}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Robert Hall", "Michael Harrison"]
  s.date = %q{2010-08-06}
  s.description = %q{Temporary fork of Robert Hall's imposter gem with Ruby 1.9 and Rails 3 support. Provides generators and rake tasks via YAML based imposters for schema level data faking}
  s.email = %q{mh@michaelharrison.ws}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/imposter_generator.rb",
     "generators/templates/databases.rake",
     "id_rsa.pub",
     "lib/generators/imposter.rb",
     "lib/generators/imposter/gen_models/gen_models_generator.rb",
     "lib/generators/imposter/install/install_generator.rb",
     "lib/generators/imposter/install/templates/databases.rake",
     "lib/generators/imposter/install/templates/models.yml",
     "lib/imposter.rb",
     "lib/imposter/animal.rb",
     "lib/imposter/csz.db",
     "lib/imposter/csz.rb",
     "lib/imposter/mineral.rb",
     "lib/imposter/noun.rb",
     "lib/imposter/phone.rb",
     "lib/imposter/vegetable.rb",
     "lib/imposter/verb.rb",
     "lib/imposter/version.rb",
     "test/helper.rb",
     "test/test_imposter.rb",
     "urlsplease-imposter.gemspec"
  ]
  s.homepage = %q{http://github.com/urlsplease/imposter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{(Ruby 1.9 and Rails 3 ready) Real fake data}
  s.test_files = [
    "test/helper.rb",
     "test/test_imposter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 1.2.5"])
      s.add_runtime_dependency(%q<faker>, [">= 0"])
      s.add_runtime_dependency(%q<fastercsv>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 1.2.5"])
      s.add_dependency(%q<faker>, [">= 0"])
      s.add_dependency(%q<fastercsv>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 1.2.5"])
    s.add_dependency(%q<faker>, [">= 0"])
    s.add_dependency(%q<fastercsv>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

